/**
 * TripPilot AI — Verified Transport Connections & Graph Edges
 * Authentic train, bus, and cab schedules between Indian cities and transport hubs.
 */

export const CONNECTIONS = [
  // =========================================================================
  // 1. SIVAKASI <-> MADURAI (Crucial feeder corridor for South Tamil Nadu)
  // =========================================================================
  {
    from: 'sivakasi',
    to: 'madurai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12662',
    name: 'Pothigai Superfast Express',
    classes: ['2S', 'SL', '3A'],
    departure: '07:15 PM',
    arrival: '08:40 PM',
    durationMinutes: 85,
    fare: 115,
    comfort: 'Medium',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Sivakasi Railway Station (SVKS)',
    toStation: 'Madurai Junction (MDU)',
  },
  {
    from: 'sivakasi',
    to: 'madurai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '06652',
    name: 'Sengottai - Madurai Passenger Express',
    classes: ['2S'],
    departure: '08:35 AM',
    arrival: '10:15 AM',
    durationMinutes: 100,
    fare: 45,
    comfort: 'Economy',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Sivakasi Railway Station (SVKS)',
    toStation: 'Madurai Junction (MDU)',
  },
  {
    from: 'sivakasi',
    to: 'madurai',
    mode: 'bus',
    provider: 'TNSTC / State Transport',
    name: 'TNSTC Non-Stop Point-to-Point Express',
    classes: ['Standard Express'],
    departure: '06:30 AM',
    arrival: '08:15 AM',
    durationMinutes: 105,
    fare: 85,
    comfort: 'Economy',
    bookingUrl: 'https://www.tnstc.in',
    fromStation: 'Sivakasi Bus Stand',
    toStation: 'Madurai Mattuthavani Integrated Bus Terminal',
  },
  {
    from: 'sivakasi',
    to: 'madurai',
    mode: 'bus',
    provider: 'RedBus Verified Operators',
    name: 'SRS Travels AC Semi-Sleeper',
    classes: ['AC Semi-Sleeper'],
    departure: '04:00 PM',
    arrival: '05:30 PM',
    durationMinutes: 90,
    fare: 220,
    comfort: 'High',
    bookingUrl: 'https://www.redbus.in',
    fromStation: 'Sivakasi Bypass',
    toStation: 'Madurai Periyar Bus Stand',
  },
  {
    from: 'sivakasi',
    to: 'madurai',
    mode: 'cab',
    provider: 'Uber Intercity / Local Taxi',
    name: 'Dedicated Intercity Sedan (Dzire)',
    classes: ['AC Sedan'],
    departure: 'Flexible on request',
    arrival: '+1h 20m',
    durationMinutes: 80,
    fare: 1650,
    comfort: 'High',
    bookingUrl: 'https://m.uber.com/looking',
    fromStation: 'Doorstep Pickup Sivakasi',
    toStation: 'Madurai Junction / Mattuthavani',
  },

  // Reverse: Madurai -> Sivakasi
  {
    from: 'madurai',
    to: 'sivakasi',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12661',
    name: 'Pothigai Superfast Express',
    classes: ['2S', 'SL', '3A'],
    departure: '06:10 AM',
    arrival: '07:28 AM',
    durationMinutes: 78,
    fare: 115,
    comfort: 'Medium',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Madurai Junction (MDU)',
    toStation: 'Sivakasi Railway Station (SVKS)',
  },
  {
    from: 'madurai',
    to: 'sivakasi',
    mode: 'bus',
    provider: 'TNSTC / State Transport',
    name: 'TNSTC Frequent Highway Express',
    classes: ['Standard Express'],
    departure: '09:00 AM',
    arrival: '10:45 AM',
    durationMinutes: 105,
    fare: 85,
    comfort: 'Economy',
    bookingUrl: 'https://www.tnstc.in',
    fromStation: 'Madurai Periyar Bus Stand',
    toStation: 'Sivakasi Bus Stand',
  },

  // =========================================================================
  // 2. MADURAI <-> HYDERABAD (Key Inter-State Hub Route)
  // =========================================================================
  {
    from: 'madurai',
    to: 'hyderabad',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '07192',
    name: 'Madurai - Kacheguda Special Superfast',
    classes: ['2A', '3A', 'SL'],
    departure: '05:30 AM',
    arrival: '07:10 AM (Next Day)',
    durationMinutes: 1540,
    fare: 1720,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Madurai Junction (MDU)',
    toStation: 'Hyderabad Kacheguda (KCG)',
  },
  {
    from: 'madurai',
    to: 'hyderabad',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '16354',
    name: 'Nagercoil - Kacheguda Weekly Express',
    classes: ['2A', '3A', 'SL'],
    departure: '01:15 PM',
    arrival: '01:25 PM (Next Day)',
    durationMinutes: 1450,
    fare: 1650,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Madurai Junction (MDU)',
    toStation: 'Hyderabad Kacheguda (KCG)',
  },
  {
    from: 'madurai',
    to: 'hyderabad',
    mode: 'bus',
    provider: 'RedBus (Orange Travels)',
    name: 'Orange Travels AC Multi-Axle Sleeper (2+1)',
    classes: ['AC Sleeper'],
    departure: '02:30 PM',
    arrival: '08:00 AM (Next Day)',
    durationMinutes: 1050,
    fare: 2150,
    comfort: 'Luxury',
    bookingUrl: 'https://www.redbus.in',
    fromStation: 'Madurai Mattuthavani Bus Stand',
    toStation: 'Hyderabad MGBS / Afzalgunj',
  },
  {
    from: 'madurai',
    to: 'hyderabad',
    mode: 'bus',
    provider: 'RedBus (Alhind Travels)',
    name: 'Alhind Multi-Axle Volvo AC Sleeper',
    classes: ['Volvo Sleeper'],
    departure: '04:15 PM',
    arrival: '09:45 AM (Next Day)',
    durationMinutes: 1050,
    fare: 1980,
    comfort: 'Luxury',
    bookingUrl: 'https://www.redbus.in',
    fromStation: 'Madurai Mattuthavani',
    toStation: 'Hyderabad Lakdikapul / Ameerpet',
  },

  // Reverse: Hyderabad -> Madurai
  {
    from: 'hyderabad',
    to: 'madurai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '16353',
    name: 'Kacheguda - Nagercoil Weekly Express',
    classes: ['2A', '3A', 'SL'],
    departure: '03:45 PM',
    arrival: '03:20 PM (Next Day)',
    durationMinutes: 1415,
    fare: 1650,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Hyderabad Kacheguda (KCG)',
    toStation: 'Madurai Junction (MDU)',
  },
  {
    from: 'hyderabad',
    to: 'madurai',
    mode: 'bus',
    provider: 'RedBus (Orange Travels)',
    name: 'Orange Travels AC Sleeper',
    classes: ['AC Sleeper'],
    departure: '04:30 PM',
    arrival: '09:30 AM (Next Day)',
    durationMinutes: 1020,
    fare: 2150,
    comfort: 'Luxury',
    bookingUrl: 'https://www.redbus.in',
    fromStation: 'Hyderabad MGBS',
    toStation: 'Madurai Mattuthavani',
  },

  // =========================================================================
  // 3. CHENNAI <-> HYDERABAD (High Traffic Inter-State Corridor)
  // =========================================================================
  {
    from: 'chennai',
    to: 'hyderabad',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12603',
    name: 'MGR Chennai Central - Hyderabad Superfast Express',
    classes: ['1A', '2A', '3A', 'SL'],
    departure: '04:45 PM',
    arrival: '05:45 AM (Next Day)',
    durationMinutes: 780,
    fare: 465,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'MGR Chennai Central (MAS)',
    toStation: 'Hyderabad Deccan (HYB)',
  },
  {
    from: 'chennai',
    to: 'hyderabad',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12759',
    name: 'Charminar Superfast Express',
    classes: ['1A', '2A', '3A', 'SL'],
    departure: '06:10 PM',
    arrival: '06:35 AM (Next Day)',
    durationMinutes: 745,
    fare: 480,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Chennai Egmore (MS)',
    toStation: 'Secunderabad Junction (SC)',
  },
  {
    from: 'chennai',
    to: 'hyderabad',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '20173',
    name: 'Vande Bharat Express',
    classes: ['CC', 'EC'],
    departure: '05:15 AM',
    arrival: '01:45 PM',
    durationMinutes: 510,
    fare: 1540,
    comfort: 'Luxury',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'MGR Chennai Central (MAS)',
    toStation: 'Secunderabad Junction (SC)',
  },
  {
    from: 'chennai',
    to: 'hyderabad',
    mode: 'bus',
    provider: 'RedBus (IntrCity SmartBus)',
    name: 'IntrCity SmartBus AC Multi-Axle Sleeper',
    classes: ['AC Sleeper (2+1)'],
    departure: '07:30 PM',
    arrival: '06:30 AM (Next Day)',
    durationMinutes: 660,
    fare: 1190,
    comfort: 'High',
    bookingUrl: 'https://www.redbus.in',
    fromStation: 'Koyambedu CMBT / Ashok Nagar',
    toStation: 'MGBS / Lakdikapul / Gachibowli',
  },
  {
    from: 'chennai',
    to: 'hyderabad',
    mode: 'bus',
    provider: 'TSRTC (Garuda Plus)',
    name: 'TSRTC Garuda Plus AC Multi-Axle',
    classes: ['Volvo AC Semi-Sleeper'],
    departure: '08:45 PM',
    arrival: '07:45 AM (Next Day)',
    durationMinutes: 660,
    fare: 1040,
    comfort: 'High',
    bookingUrl: 'https://www.tsrtconline.in',
    fromStation: 'Chennai CMBT',
    toStation: 'Hyderabad MGBS',
  },

  // Reverse: Hyderabad -> Chennai
  {
    from: 'hyderabad',
    to: 'chennai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12604',
    name: 'Hyderabad - MGR Chennai Central SF Express',
    classes: ['1A', '2A', '3A', 'SL'],
    departure: '04:55 PM',
    arrival: '05:40 AM (Next Day)',
    durationMinutes: 765,
    fare: 465,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Hyderabad Deccan (HYB)',
    toStation: 'MGR Chennai Central (MAS)',
  },
  {
    from: 'hyderabad',
    to: 'chennai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12760',
    name: 'Charminar Superfast Express',
    classes: ['1A', '2A', '3A', 'SL'],
    departure: '06:00 PM',
    arrival: '06:40 AM (Next Day)',
    durationMinutes: 760,
    fare: 480,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Secunderabad Junction (SC)',
    toStation: 'Chennai Egmore (MS)',
  },
  {
    from: 'hyderabad',
    to: 'chennai',
    mode: 'bus',
    provider: 'RedBus (IntrCity SmartBus)',
    name: 'IntrCity SmartBus AC Multi-Axle Sleeper',
    classes: ['AC Sleeper'],
    departure: '08:00 PM',
    arrival: '07:00 AM (Next Day)',
    durationMinutes: 660,
    fare: 1190,
    comfort: 'High',
    bookingUrl: 'https://www.redbus.in',
    fromStation: 'Gachibowli / Ameerpet / MGBS',
    toStation: 'Chennai CMBT',
  },

  // =========================================================================
  // 4. CHENNAI <-> BENGALURU
  // =========================================================================
  {
    from: 'chennai',
    to: 'bengaluru',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '20607',
    name: 'Chennai - Mysuru Vande Bharat Express',
    classes: ['CC', 'EC'],
    departure: '05:50 AM',
    arrival: '10:20 AM',
    durationMinutes: 270,
    fare: 995,
    comfort: 'Luxury',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'MGR Chennai Central (MAS)',
    toStation: 'KSR Bengaluru City (SBC)',
  },
  {
    from: 'chennai',
    to: 'bengaluru',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12007',
    name: 'Chennai - Mysuru Shatabdi Express',
    classes: ['CC', 'EC'],
    departure: '06:00 AM',
    arrival: '10:45 AM',
    durationMinutes: 285,
    fare: 910,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'MGR Chennai Central (MAS)',
    toStation: 'KSR Bengaluru City (SBC)',
  },
  {
    from: 'chennai',
    to: 'bengaluru',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '22625',
    name: 'Chennai - KSR Bengaluru Double Decker Express',
    classes: ['CC'],
    departure: '07:25 AM',
    arrival: '01:10 PM',
    durationMinutes: 345,
    fare: 460,
    comfort: 'Medium',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'MGR Chennai Central (MAS)',
    toStation: 'KSR Bengaluru City (SBC)',
  },
  {
    from: 'chennai',
    to: 'bengaluru',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12609',
    name: 'MGR Chennai Central - Mysuru SF Express',
    classes: ['2S', 'CC'],
    departure: '01:35 PM',
    arrival: '07:45 PM',
    durationMinutes: 370,
    fare: 175,
    comfort: 'Economy',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'MGR Chennai Central (MAS)',
    toStation: 'KSR Bengaluru City (SBC)',
  },
  {
    from: 'chennai',
    to: 'bengaluru',
    mode: 'bus',
    provider: 'KSRTC (Airavat Club Class)',
    name: 'KSRTC Airavat Multi-Axle Volvo AC',
    classes: ['Volvo AC Semi-Sleeper'],
    departure: '10:30 PM',
    arrival: '05:30 AM (Next Day)',
    durationMinutes: 420,
    fare: 680,
    comfort: 'High',
    bookingUrl: 'https://www.ksrtc.in',
    fromStation: 'Koyambedu CMBT',
    toStation: 'Majestic / Shantinagar / Electronic City',
  },
  {
    from: 'chennai',
    to: 'bengaluru',
    mode: 'cab',
    provider: 'MakeMyTrip Intercity Cabs',
    name: 'Expressway Intercity Sedan (Dzire)',
    classes: ['AC Sedan'],
    departure: 'Flexible on request',
    arrival: '+5h 30m',
    durationMinutes: 330,
    fare: 4800,
    comfort: 'High',
    bookingUrl: 'https://www.makemytrip.com/cabs/',
    fromStation: 'Doorstep Pickup Chennai',
    toStation: 'Direct Drop Bengaluru',
  },

  // Reverse: Bengaluru -> Chennai
  {
    from: 'bengaluru',
    to: 'chennai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '20608',
    name: 'Mysuru - Chennai Vande Bharat Express',
    classes: ['CC', 'EC'],
    departure: '02:50 PM',
    arrival: '07:30 PM',
    durationMinutes: 280,
    fare: 995,
    comfort: 'Luxury',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'KSR Bengaluru City (SBC)',
    toStation: 'MGR Chennai Central (MAS)',
  },
  {
    from: 'bengaluru',
    to: 'chennai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12008',
    name: 'Mysuru - Chennai Shatabdi Express',
    classes: ['CC', 'EC'],
    departure: '04:25 PM',
    arrival: '09:30 PM',
    durationMinutes: 305,
    fare: 910,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'KSR Bengaluru City (SBC)',
    toStation: 'MGR Chennai Central (MAS)',
  },
  {
    from: 'bengaluru',
    to: 'chennai',
    mode: 'bus',
    provider: 'KSRTC (Airavat Club Class)',
    name: 'KSRTC Airavat Multi-Axle Volvo AC',
    classes: ['Volvo AC Semi-Sleeper'],
    departure: '11:00 PM',
    arrival: '06:00 AM (Next Day)',
    durationMinutes: 420,
    fare: 680,
    comfort: 'High',
    bookingUrl: 'https://www.ksrtc.in',
    fromStation: 'Majestic Bus Stand',
    toStation: 'Koyambedu CMBT',
  },

  // =========================================================================
  // 5. COIMBATORE <-> CHENNAI
  // =========================================================================
  {
    from: 'coimbatore',
    to: 'chennai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '20644',
    name: 'Coimbatore - Chennai Vande Bharat Express',
    classes: ['CC', 'EC'],
    departure: '06:00 AM',
    arrival: '11:50 AM',
    durationMinutes: 350,
    fare: 1365,
    comfort: 'Luxury',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Coimbatore Junction (CBE)',
    toStation: 'MGR Chennai Central (MAS)',
  },
  {
    from: 'coimbatore',
    to: 'chennai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12676',
    name: 'Kovai Superfast Express',
    classes: ['CC', '2S'],
    departure: '03:15 PM',
    arrival: '10:50 PM',
    durationMinutes: 455,
    fare: 235,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Coimbatore Junction (CBE)',
    toStation: 'MGR Chennai Central (MAS)',
  },
  {
    from: 'coimbatore',
    to: 'chennai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12672',
    name: 'Nilgiri Superfast Express (Sleeper)',
    classes: ['1A', '2A', '3A', 'SL'],
    departure: '10:20 PM',
    arrival: '06:25 AM (Next Day)',
    durationMinutes: 485,
    fare: 345,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Coimbatore Junction (CBE)',
    toStation: 'MGR Chennai Central (MAS)',
  },
  {
    from: 'coimbatore',
    to: 'chennai',
    mode: 'bus',
    provider: 'RedBus (IntrCity SmartBus)',
    name: 'IntrCity SmartBus Multi-Axle AC Sleeper',
    classes: ['AC Sleeper'],
    departure: '10:00 PM',
    arrival: '06:15 AM (Next Day)',
    durationMinutes: 495,
    fare: 750,
    comfort: 'High',
    bookingUrl: 'https://www.redbus.in',
    fromStation: 'Gandhipuram / Omni Bus Stand',
    toStation: 'Kilambakkam KCBT / Koyambedu CMBT',
  },
  {
    from: 'coimbatore',
    to: 'chennai',
    mode: 'bus',
    provider: 'SETC / State Express',
    name: 'SETC Ultra Deluxe Non-AC',
    classes: ['Ultra Deluxe (2+2)'],
    departure: '08:30 PM',
    arrival: '06:00 AM (Next Day)',
    durationMinutes: 570,
    fare: 450,
    comfort: 'Economy',
    bookingUrl: 'https://www.tnstc.in',
    fromStation: 'Coimbatore Gandhipuram SETC Stand',
    toStation: 'Kilambakkam KCBT',
  },

  // Reverse: Chennai -> Coimbatore
  {
    from: 'chennai',
    to: 'coimbatore',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '20643',
    name: 'Chennai - Coimbatore Vande Bharat Express',
    classes: ['CC', 'EC'],
    departure: '02:25 PM',
    arrival: '08:15 PM',
    durationMinutes: 350,
    fare: 1365,
    comfort: 'Luxury',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'MGR Chennai Central (MAS)',
    toStation: 'Coimbatore Junction (CBE)',
  },
  {
    from: 'chennai',
    to: 'coimbatore',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12675',
    name: 'Kovai Superfast Express',
    classes: ['CC', '2S'],
    departure: '06:10 AM',
    arrival: '02:05 PM',
    durationMinutes: 475,
    fare: 235,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'MGR Chennai Central (MAS)',
    toStation: 'Coimbatore Junction (CBE)',
  },

  // =========================================================================
  // 6. COIMBATORE <-> HYDERABAD
  // =========================================================================
  {
    from: 'coimbatore',
    to: 'hyderabad',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12647',
    name: 'Kongu Superfast Express',
    classes: ['2A', '3A', 'SL'],
    departure: '03:05 PM',
    arrival: '10:40 AM (Next Day)',
    durationMinutes: 1175,
    fare: 1480,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Coimbatore Junction (CBE)',
    toStation: 'Hyderabad Kacheguda (KCG)',
  },
  {
    from: 'coimbatore',
    to: 'hyderabad',
    mode: 'bus',
    provider: 'RedBus (Orange Travels)',
    name: 'Orange Travels Bharat Benz AC Sleeper (2+1)',
    classes: ['AC Sleeper'],
    departure: '03:45 PM',
    arrival: '07:30 AM (Next Day)',
    durationMinutes: 945,
    fare: 1850,
    comfort: 'Luxury',
    bookingUrl: 'https://www.redbus.in',
    fromStation: 'Gandhipuram / Hopes College',
    toStation: 'Hyderabad MGBS / Lakdikapul',
  },

  // Reverse: Hyderabad -> Coimbatore
  {
    from: 'hyderabad',
    to: 'coimbatore',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12648',
    name: 'Kongu Superfast Express',
    classes: ['2A', '3A', 'SL'],
    departure: '08:20 AM',
    arrival: '06:30 AM (Next Day)',
    durationMinutes: 1330,
    fare: 1480,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Hyderabad Kacheguda (KCG)',
    toStation: 'Coimbatore Junction (CBE)',
  },

  // =========================================================================
  // 7. TIRUNELVELI <-> CHENNAI
  // =========================================================================
  {
    from: 'tirunelveli',
    to: 'chennai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '20666',
    name: 'Tirunelveli - Chennai Egmore Vande Bharat Express',
    classes: ['CC', 'EC'],
    departure: '06:00 AM',
    arrival: '01:50 PM',
    durationMinutes: 470,
    fare: 1655,
    comfort: 'Luxury',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Tirunelveli Junction (TEN)',
    toStation: 'Chennai Egmore (MS)',
  },
  {
    from: 'tirunelveli',
    to: 'chennai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12632',
    name: 'Nellai Superfast Express',
    classes: ['1A', '2A', '3A', 'SL'],
    departure: '07:55 PM',
    arrival: '07:00 AM (Next Day)',
    durationMinutes: 665,
    fare: 410,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Tirunelveli Junction (TEN)',
    toStation: 'Chennai Egmore (MS)',
  },
  {
    from: 'tirunelveli',
    to: 'chennai',
    mode: 'bus',
    provider: 'SETC / State Express',
    name: 'SETC Multi-Axle AC Sleeper Bus',
    classes: ['AC Sleeper'],
    departure: '08:15 PM',
    arrival: '06:45 AM (Next Day)',
    durationMinutes: 630,
    fare: 890,
    comfort: 'High',
    bookingUrl: 'https://www.tnstc.in',
    fromStation: 'Tirunelveli New Bus Stand',
    toStation: 'Kilambakkam KCBT',
  },

  // Reverse: Chennai -> Tirunelveli
  {
    from: 'chennai',
    to: 'tirunelveli',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '20665',
    name: 'Chennai Egmore - Tirunelveli Vande Bharat Express',
    classes: ['CC', 'EC'],
    departure: '02:50 PM',
    arrival: '10:40 PM',
    durationMinutes: 470,
    fare: 1655,
    comfort: 'Luxury',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Chennai Egmore (MS)',
    toStation: 'Tirunelveli Junction (TEN)',
  },
  {
    from: 'chennai',
    to: 'tirunelveli',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12631',
    name: 'Nellai Superfast Express',
    classes: ['1A', '2A', '3A', 'SL'],
    departure: '08:10 PM',
    arrival: '06:40 AM (Next Day)',
    durationMinutes: 630,
    fare: 410,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Chennai Egmore (MS)',
    toStation: 'Tirunelveli Junction (TEN)',
  },

  // =========================================================================
  // 8. TIRUNELVELI <-> BENGALURU
  // =========================================================================
  {
    from: 'tirunelveli',
    to: 'bengaluru',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '17236',
    name: 'Nagercoil - SMVT Bengaluru Express',
    classes: ['2A', '3A', 'SL'],
    departure: '09:05 PM',
    arrival: '09:15 AM (Next Day)',
    durationMinutes: 730,
    fare: 440,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Tirunelveli Junction (TEN)',
    toStation: 'SMVT Bengaluru (SMVB)',
  },
  {
    from: 'tirunelveli',
    to: 'bengaluru',
    mode: 'bus',
    provider: 'KSRTC (Airavat Club Class)',
    name: 'KSRTC Multi-Axle Volvo AC Sleeper',
    classes: ['Volvo AC Sleeper'],
    departure: '07:30 PM',
    arrival: '06:45 AM (Next Day)',
    durationMinutes: 675,
    fare: 1150,
    comfort: 'High',
    bookingUrl: 'https://www.ksrtc.in',
    fromStation: 'Tirunelveli New Bus Stand',
    toStation: 'Majestic / Shantinagar / Madiwala',
  },

  // Reverse: Bengaluru -> Tirunelveli
  {
    from: 'bengaluru',
    to: 'tirunelveli',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '17235',
    name: 'SMVT Bengaluru - Nagercoil Express',
    classes: ['2A', '3A', 'SL'],
    departure: '05:00 PM',
    arrival: '05:35 AM (Next Day)',
    durationMinutes: 755,
    fare: 440,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'SMVT Bengaluru (SMVB)',
    toStation: 'Tirunelveli Junction (TEN)',
  },

  // =========================================================================
  // 9. SALEM <-> BENGALURU
  // =========================================================================
  {
    from: 'salem',
    to: 'bengaluru',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12678',
    name: 'Ernakulam - KSR Bengaluru InterCity SF',
    classes: ['CC', '2S'],
    departure: '03:55 PM',
    arrival: '07:50 PM',
    durationMinutes: 235,
    fare: 145,
    comfort: 'Medium',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Salem Junction (SA)',
    toStation: 'KSR Bengaluru City (SBC)',
  },
  {
    from: 'salem',
    to: 'bengaluru',
    mode: 'bus',
    provider: 'KSRTC (Airavat Club Class)',
    name: 'KSRTC Airavat Multi-Axle Volvo',
    classes: ['Volvo AC Semi-Sleeper'],
    departure: '02:00 PM',
    arrival: '06:15 PM',
    durationMinutes: 255,
    fare: 480,
    comfort: 'High',
    bookingUrl: 'https://www.ksrtc.in',
    fromStation: 'Salem New Bus Stand',
    toStation: 'Electronic City / Shantinagar / Majestic',
  },
  {
    from: 'salem',
    to: 'bengaluru',
    mode: 'cab',
    provider: 'MakeMyTrip Intercity Cabs',
    name: 'Dedicated Expressway Sedan',
    classes: ['AC Sedan'],
    departure: 'Flexible on request',
    arrival: '+3h 45m',
    durationMinutes: 225,
    fare: 3100,
    comfort: 'High',
    bookingUrl: 'https://www.makemytrip.com/cabs/',
    fromStation: 'Doorstep Pickup Salem',
    toStation: 'Direct Drop Bengaluru',
  },

  // Reverse: Bengaluru -> Salem
  {
    from: 'bengaluru',
    to: 'salem',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12677',
    name: 'KSR Bengaluru - Ernakulam InterCity SF',
    classes: ['CC', '2S'],
    departure: '06:10 AM',
    arrival: '10:02 AM',
    durationMinutes: 232,
    fare: 145,
    comfort: 'Medium',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'KSR Bengaluru City (SBC)',
    toStation: 'Salem Junction (SA)',
  },

  // =========================================================================
  // 10. ERODE <-> CHENNAI
  // =========================================================================
  {
    from: 'erode',
    to: 'chennai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12676',
    name: 'Kovai Superfast Express',
    classes: ['CC', '2S'],
    departure: '04:10 PM',
    arrival: '10:50 PM',
    durationMinutes: 400,
    fare: 195,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Erode Junction (ED)',
    toStation: 'MGR Chennai Central (MAS)',
  },
  {
    from: 'erode',
    to: 'chennai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12672',
    name: 'Nilgiri Superfast Express (Sleeper)',
    classes: ['1A', '2A', '3A', 'SL'],
    departure: '11:30 PM',
    arrival: '06:25 AM (Next Day)',
    durationMinutes: 415,
    fare: 310,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Erode Junction (ED)',
    toStation: 'MGR Chennai Central (MAS)',
  },
  {
    from: 'erode',
    to: 'chennai',
    mode: 'bus',
    provider: 'SETC / State Express',
    name: 'SETC Ultra Deluxe AC Express',
    classes: ['Ultra Deluxe (2+2)'],
    departure: '09:45 PM',
    arrival: '05:30 AM (Next Day)',
    durationMinutes: 465,
    fare: 460,
    comfort: 'Economy',
    bookingUrl: 'https://www.tnstc.in',
    fromStation: 'Erode Central Bus Stand',
    toStation: 'Kilambakkam KCBT',
  },

  // Reverse: Chennai -> Erode
  {
    from: 'chennai',
    to: 'erode',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12675',
    name: 'Kovai Superfast Express',
    classes: ['CC', '2S'],
    departure: '06:10 AM',
    arrival: '12:05 PM',
    durationMinutes: 355,
    fare: 195,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'MGR Chennai Central (MAS)',
    toStation: 'Erode Junction (ED)',
  },

  // =========================================================================
  // 11. MUMBAI <-> HYDERABAD
  // =========================================================================
  {
    from: 'mumbai',
    to: 'hyderabad',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12701',
    name: 'Hussain Sagar Superfast Express',
    classes: ['1A', '2A', '3A', 'SL'],
    departure: '09:50 PM',
    arrival: '12:05 PM (Next Day)',
    durationMinutes: 855,
    fare: 450,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Mumbai CSMT (CSMT)',
    toStation: 'Hyderabad Deccan (HYB)',
  },
  {
    from: 'mumbai',
    to: 'hyderabad',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '17031',
    name: 'Mumbai CSMT - Hyderabad Express',
    classes: ['2A', '3A', 'SL'],
    departure: '02:10 PM',
    arrival: '05:30 AM (Next Day)',
    durationMinutes: 920,
    fare: 420,
    comfort: 'Medium',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Mumbai CSMT (CSMT)',
    toStation: 'Hyderabad Deccan (HYB)',
  },
  {
    from: 'mumbai',
    to: 'hyderabad',
    mode: 'bus',
    provider: 'RedBus (VRL Travels)',
    name: 'VRL Multi-Axle AC Sleeper (2+1)',
    classes: ['AC Sleeper'],
    departure: '05:30 PM',
    arrival: '07:30 AM (Next Day)',
    durationMinutes: 840,
    fare: 1250,
    comfort: 'High',
    bookingUrl: 'https://www.redbus.in',
    fromStation: 'Borivali / Vashi / Sion',
    toStation: 'Miyapur / Ameerpet / MGBS',
  },

  // Reverse: Hyderabad -> Mumbai
  {
    from: 'hyderabad',
    to: 'mumbai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12702',
    name: 'Hussain Sagar Superfast Express',
    classes: ['1A', '2A', '3A', 'SL'],
    departure: '02:50 PM',
    arrival: '04:55 AM (Next Day)',
    durationMinutes: 845,
    fare: 450,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Hyderabad Deccan (HYB)',
    toStation: 'Mumbai CSMT (CSMT)',
  },

  // =========================================================================
  // 12. DELHI <-> MUMBAI
  // =========================================================================
  {
    from: 'delhi',
    to: 'mumbai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12952',
    name: 'New Delhi - Mumbai Central Tejas Rajdhani Express',
    classes: ['1A', '2A', '3A'],
    departure: '04:55 PM',
    arrival: '08:35 AM (Next Day)',
    durationMinutes: 940,
    fare: 2450,
    comfort: 'Luxury',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'New Delhi (NDLS)',
    toStation: 'Mumbai Central (MMCT)',
  },
  {
    from: 'delhi',
    to: 'mumbai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12954',
    name: 'August Kranti Tejas Rajdhani Express',
    classes: ['1A', '2A', '3A'],
    departure: '05:15 PM',
    arrival: '10:05 AM (Next Day)',
    durationMinutes: 1010,
    fare: 2380,
    comfort: 'Luxury',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Hazrat Nizamuddin (NZM)',
    toStation: 'Mumbai Central (MMCT)',
  },

  // Reverse: Mumbai -> Delhi
  {
    from: 'mumbai',
    to: 'delhi',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12951',
    name: 'Mumbai Central - New Delhi Tejas Rajdhani Express',
    classes: ['1A', '2A', '3A'],
    departure: '05:00 PM',
    arrival: '08:32 AM (Next Day)',
    durationMinutes: 932,
    fare: 2450,
    comfort: 'Luxury',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Mumbai Central (MMCT)',
    toStation: 'New Delhi (NDLS)',
  },

  // =========================================================================
  // 13. KOCHI <-> CHENNAI
  // =========================================================================
  {
    from: 'kochi',
    to: 'chennai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12624',
    name: 'Thiruvananthapuram - Chennai Central Mail',
    classes: ['1A', '2A', '3A', 'SL'],
    departure: '07:25 PM',
    arrival: '07:45 AM (Next Day)',
    durationMinutes: 740,
    fare: 460,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Ernakulam Junction (ERS)',
    toStation: 'MGR Chennai Central (MAS)',
  },
  {
    from: 'kochi',
    to: 'chennai',
    mode: 'bus',
    provider: 'RedBus (Kallada Travels)',
    name: 'Kallada Multi-Axle AC Sleeper (2+1)',
    classes: ['AC Sleeper'],
    departure: '06:00 PM',
    arrival: '07:30 AM (Next Day)',
    durationMinutes: 810,
    fare: 1350,
    comfort: 'High',
    bookingUrl: 'https://www.redbus.in',
    fromStation: 'Ernakulam Vyttila Hub',
    toStation: 'Koyambedu CMBT',
  },

  // Reverse: Chennai -> Kochi
  {
    from: 'chennai',
    to: 'kochi',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12623',
    name: 'Chennai Central - Thiruvananthapuram Mail',
    classes: ['1A', '2A', '3A', 'SL'],
    departure: '07:45 PM',
    arrival: '08:05 AM (Next Day)',
    durationMinutes: 740,
    fare: 460,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'MGR Chennai Central (MAS)',
    toStation: 'Ernakulam Junction (ERS)',
  },

  // =========================================================================
  // 14. BENGALURU <-> HYDERABAD
  // =========================================================================
  {
    from: 'bengaluru',
    to: 'hyderabad',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '20704',
    name: 'Kacheguda Vande Bharat Express',
    classes: ['CC', 'EC'],
    departure: '02:45 PM',
    arrival: '11:00 PM',
    durationMinutes: 495,
    fare: 1540,
    comfort: 'Luxury',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Yesvantpur Junction (YPR)',
    toStation: 'Hyderabad Kacheguda (KCG)',
  },
  {
    from: 'bengaluru',
    to: 'hyderabad',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12786',
    name: 'Kacheguda Superfast Express',
    classes: ['1A', '2A', '3A', 'SL'],
    departure: '06:30 PM',
    arrival: '05:40 AM (Next Day)',
    durationMinutes: 670,
    fare: 435,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'KSR Bengaluru City (SBC)',
    toStation: 'Hyderabad Kacheguda (KCG)',
  },
  {
    from: 'bengaluru',
    to: 'hyderabad',
    mode: 'bus',
    provider: 'KSRTC (Airavat Club Class)',
    name: 'KSRTC Multi-Axle Volvo AC Sleeper',
    classes: ['Volvo AC Sleeper'],
    departure: '10:00 PM',
    arrival: '06:30 AM (Next Day)',
    durationMinutes: 510,
    fare: 980,
    comfort: 'High',
    bookingUrl: 'https://www.ksrtc.in',
    fromStation: 'Majestic / Hebbal / Yelahanka',
    toStation: 'Shamshabad / Afzalgunj / MGBS',
  },

  // Reverse: Hyderabad -> Bengaluru
  {
    from: 'hyderabad',
    to: 'bengaluru',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '20703',
    name: 'Kacheguda - Yesvantpur Vande Bharat Express',
    classes: ['CC', 'EC'],
    departure: '05:45 AM',
    arrival: '02:00 PM',
    durationMinutes: 495,
    fare: 1540,
    comfort: 'Luxury',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Hyderabad Kacheguda (KCG)',
    toStation: 'Yesvantpur Junction (YPR)',
  },

  // =========================================================================
  // 15. MADURAI <-> MUMBAI
  // =========================================================================
  {
    from: 'madurai',
    to: 'mumbai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '16352',
    name: 'Nagercoil - Mumbai CSMT Express (via Madurai)',
    classes: ['2A', '3A', 'SL'],
    departure: '09:30 AM',
    arrival: '07:15 PM (Next Day)',
    durationMinutes: 2025,
    fare: 890,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Madurai Junction (MDU)',
    toStation: 'Mumbai CSMT (CSMT)',
  },

  // Reverse: Mumbai -> Madurai
  {
    from: 'mumbai',
    to: 'madurai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '16351',
    name: 'Mumbai CSMT - Nagercoil Express (via Madurai)',
    classes: ['2A', '3A', 'SL'],
    departure: '08:30 PM',
    arrival: '05:25 AM (Day 3)',
    durationMinutes: 1975,
    fare: 890,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Mumbai CSMT (CSMT)',
    toStation: 'Madurai Junction (MDU)',
  },

  // =========================================================================
  // 16. MADURAI <-> DELHI
  // =========================================================================
  {
    from: 'madurai',
    to: 'delhi',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12651',
    name: 'Tamil Nadu Sampark Kranti Express',
    classes: ['1A', '2A', '3A', 'SL'],
    departure: '00:55 AM',
    arrival: '06:00 PM (Next Day)',
    durationMinutes: 2465,
    fare: 1140,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Madurai Junction (MDU)',
    toStation: 'Hazrat Nizamuddin (NZM)',
  },

  // Reverse: Delhi -> Madurai
  {
    from: 'delhi',
    to: 'madurai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12652',
    name: 'Tamil Nadu Sampark Kranti Express',
    classes: ['1A', '2A', '3A', 'SL'],
    departure: '05:20 AM',
    arrival: '11:55 PM (Next Day)',
    durationMinutes: 2555,
    fare: 1140,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Hazrat Nizamuddin (NZM)',
    toStation: 'Madurai Junction (MDU)',
  },

  // =========================================================================
  // 17. COIMBATORE <-> MUMBAI
  // =========================================================================
  {
    from: 'coimbatore',
    to: 'mumbai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '11014',
    name: 'Coimbatore - Lokmanya Tilak Express',
    classes: ['2A', '3A', 'SL'],
    departure: '08:50 AM',
    arrival: '01:55 PM (Next Day)',
    durationMinutes: 1745,
    fare: 720,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Coimbatore Junction (CBE)',
    toStation: 'Lokmanya Tilak Terminus (LTT)',
  },

  // Reverse: Mumbai -> Coimbatore
  {
    from: 'mumbai',
    to: 'coimbatore',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '11013',
    name: 'Lokmanya Tilak - Coimbatore Express',
    classes: ['2A', '3A', 'SL'],
    departure: '10:35 PM',
    arrival: '07:00 AM (Day 3)',
    durationMinutes: 1945,
    fare: 720,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Lokmanya Tilak Terminus (LTT)',
    toStation: 'Coimbatore Junction (CBE)',
  },

  // =========================================================================
  // 18. SALEM <-> HYDERABAD
  // =========================================================================
  {
    from: 'salem',
    to: 'hyderabad',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12789',
    name: 'Kacheguda Superfast Express (via Salem)',
    classes: ['2A', '3A', 'SL'],
    departure: '06:10 PM',
    arrival: '10:40 AM (Next Day)',
    durationMinutes: 990,
    fare: 540,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Salem Junction (SA)',
    toStation: 'Hyderabad Kacheguda (KCG)',
  },
  {
    from: 'salem',
    to: 'hyderabad',
    mode: 'bus',
    provider: 'RedBus (Orange Travels)',
    name: 'Orange Travels AC Sleeper',
    classes: ['AC Sleeper'],
    departure: '06:30 PM',
    arrival: '07:30 AM (Next Day)',
    durationMinutes: 780,
    fare: 1650,
    comfort: 'Luxury',
    bookingUrl: 'https://www.redbus.in',
    fromStation: 'Salem New Bus Stand',
    toStation: 'MGBS / Lakdikapul',
  },

  // =========================================================================
  // 19. MADURAI <-> CHENNAI
  // =========================================================================
  {
    from: 'madurai',
    to: 'chennai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '20636',
    name: 'Madurai - Chennai Egmore Vande Bharat Express',
    classes: ['CC', 'EC'],
    departure: '07:50 AM',
    arrival: '02:00 PM',
    durationMinutes: 370,
    fare: 1465,
    comfort: 'Luxury',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Madurai Junction (MDU)',
    toStation: 'Chennai Egmore (MS)',
  },
  {
    from: 'madurai',
    to: 'chennai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12636',
    name: 'Vaigai Superfast Express',
    classes: ['CC', '2S'],
    departure: '07:05 AM',
    arrival: '02:40 PM',
    durationMinutes: 455,
    fare: 210,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Madurai Junction (MDU)',
    toStation: 'Chennai Egmore (MS)',
  },
  {
    from: 'madurai',
    to: 'chennai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12638',
    name: 'Pandian Superfast Express',
    classes: ['1A', '2A', '3A', 'SL'],
    departure: '09:20 PM',
    arrival: '05:15 AM (Next Day)',
    durationMinutes: 475,
    fare: 350,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Madurai Junction (MDU)',
    toStation: 'Chennai Egmore (MS)',
  },
  {
    from: 'madurai',
    to: 'chennai',
    mode: 'bus',
    provider: 'SETC / State Express',
    name: 'SETC Multi-Axle AC Sleeper Bus',
    classes: ['AC Sleeper'],
    departure: '09:30 PM',
    arrival: '06:00 AM (Next Day)',
    durationMinutes: 510,
    fare: 750,
    comfort: 'High',
    bookingUrl: 'https://www.tnstc.in',
    fromStation: 'Madurai Mattuthavani Bus Stand',
    toStation: 'Kilambakkam KCBT',
  },

  // Reverse: Chennai -> Madurai
  {
    from: 'chennai',
    to: 'madurai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '20635',
    name: 'Chennai Egmore - Madurai Vande Bharat Express',
    classes: ['CC', 'EC'],
    departure: '05:45 AM',
    arrival: '12:00 PM',
    durationMinutes: 375,
    fare: 1465,
    comfort: 'Luxury',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Chennai Egmore (MS)',
    toStation: 'Madurai Junction (MDU)',
  },
  {
    from: 'chennai',
    to: 'madurai',
    mode: 'train',
    provider: 'Indian Railways (IRCTC)',
    trainNumber: '12637',
    name: 'Pandian Superfast Express',
    classes: ['1A', '2A', '3A', 'SL'],
    departure: '09:40 PM',
    arrival: '05:35 AM (Next Day)',
    durationMinutes: 475,
    fare: 350,
    comfort: 'High',
    bookingUrl: 'https://www.irctc.co.in/nget/train-search',
    fromStation: 'Chennai Egmore (MS)',
    toStation: 'Madurai Junction (MDU)',
  },
];
